name: Build Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.8
        activate-environment: minimax-env
    
    - name: Install dependencies with conda
      shell: bash -l {0}
      run: |
        conda install -c conda-forge numpy=1.23.5 pandas=1.5.3 pillow openpyxl requests
        conda install -c conda-forge pyinstaller
    
    - name: Build with PyInstaller
      shell: bash -l {0}
      run: |
        pyinstaller --onefile --runtime-hook=hook.py --name MiniMaxVideoGenerator main.py
    
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: MiniMaxVideoGenerator
        path: dist/MiniMaxVideoGenerator.exe
