name: Build Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
    
    - name: Build with PyInstaller
  run: |
    pyinstaller --onefile --windowed --runtime-hook=hook.py --hidden-import=numpy --hidden-import=pandas._libs.interval --hidden-import=pandas._libs.lib --name MiniMaxVideoGenerator main.py
    
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: MiniMaxVideoGenerator
        path: dist/MiniMaxVideoGenerator.exe
